### ISSUE TITLE
Link vers la map en cliquant dessus

### ISSUE THREAD

**Issue by unixfox** [Alan736/NotCardinalPGM#2]
Via le XML pouvoir mettre un lien vers la map sur le forum. Grâce à cela lors d'un /map on peut cliquer sur la map et ensuite redirigé vers le topic.

**Comment by Narekushia** [comment]
Comme cela n'existe pas dans la [documentation officielle](https://docs.oc.tc/), il faudrait modifier tous les XML un par un en trouvant un lien qui pourra par la suite être supprimé. C'est donc beaucoup de boulot pour presque rien.
